version: '3'
services:
  web:
    image: elenamaria/hello-app
    command: bash -c "bundle exec rails webpacker:install && rails db:create && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - bundle-volume:/usr/local/bundle
      - ./costum.yml:/app/config/costum.yml
    ports:
      - "3000:3000"
    depends_on: 
      - db  
  
  db:
    image: postgres:12
    volumes: 
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: treidezero

volumes:
  bundle-volume:
  db-volume:
